# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-56d1g.eastus.azure.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=EB7WALGHXBBQQZLK
sasl.password=cfltdULMPH4vqdP66rX61TLpyK7Shn/8tnxrGeksv1hlWTvgUOc038Jub8mME/FQ

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-python-client-6d51c2c3-3a77-4def-b045-5f240ee21675
